Fixed i_vars when numpy array
Rambatino/Kruskals pull request #9
Opened 2017-05-06 10:01 UTC by Rambatino

2017-05-06 11:02 UTC, xulaus approved these changes

2017-05-06 11:03 UTC, Rambatino commented
I want to spec the method below it actually

2017-05-06 19:49 UTC, xulaus requested changes

2017-05-06 19:49 UTC, xulaus commented on tests/test_kruskals.py
> +    try:
This won't catch the case where an error isn't thrown, but is expected. I think you want
```python
with pytest.raises(ValueError) as e:
    Kruskals.Kruskals(ndarr, exp_driver_score, i_vars=i_vars).driver_score_to_series()
assert 'not sufficient for ndarray of shape' in e.value
```

2017-05-07 11:32 UTC, xulaus approved these changes

2017-05-07 17:11 UTC, merged